name: Build dist

on:
  push:
    branches:
      - "**"
    paths:
      - "src/**/*.json"
      - "artist.schema.json"
      - ".github/scripts/build-dist.js"
      - ".github/workflows/build-dist.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "src/**/*.json"
      - "artist.schema.json"
      - ".github/scripts/build-dist.js"
      - ".github/workflows/build-dist.yml"
  workflow_dispatch:

jobs:
  validate_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Needed to push commits

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

        # Compile dist file
      - name: Build dist/artists.json
        run: node .github/scripts/build-dist-artists.js

        # Only commit if not a pull request
      - name: Commit and push changes
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && success()
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'Auto-build: update dist/artists.json'
          file_pattern: 'src/*.json dist/artists.json'
          commit_options: '--no-verify' # skips Husky precommit task