name: Update Spotify Data

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  update_genres:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Update Spotify data
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: node .github/scripts/update-spotify-data.js

      - name: Commit and push changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'Auto-update: Spotify data'
          file_pattern: 'src/*.json'
          commit_options: '--no-verify'
